version: '3.8'

services:
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mean-network
    restart: unless-stopped

  auth-backend:
    build: ./auth-backend
    container_name: mean-auth-backend
    ports:
      - "8000:8000"
    environment:
      - AUTH_DB_URL=postgresql://myuser:mypassword@postgres-db:5432/mydatabase
    depends_on:
      - postgres-db
    networks:
      - mean-network
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: mongodb-server
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - mean-network
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: mean-backend
    ports:
      - "8080"
    environment:
      - DB_URL=mongodb://mongodb:27017/dd_db
    depends_on:
      - mongodb
    networks:
      - mean-network
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: mean-frontend
    ports:
      - "80"
    depends_on:
      - backend
    networks:
      - mean-network
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: mean-nginx
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
      - auth-backend
    networks:
      - mean-network
    restart: unless-stopped

networks:
  mean-network:
    driver: bridge

volumes:
  mongodb-data:
  postgres-data:
