apiVersion: v1
kind: Secret
metadata:
  name: mean-app-secret
  namespace: mean-app
type: Opaque
# stringData is plain-text - Kubernetes will automatically base64-encode these values
stringData:
  DB_URL: "mongodb://mongodb:27017/dd_db"
  DB_USER: "admin"
  DB_PASSWORD: "changeme123"
  POSTGRES_USER: "myuser"
  POSTGRES_PASSWORD: "mypassword"
  POSTGRES_DB: "mydatabase"
  AUTH_DB_URL: "postgresql://myuser:mypassword@postgres-db:5432/mydatabase"
